spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: prod

  application:
    name: Session-Based Task Tracker


  datasource:
    url: jdbc:mysql://localhost:3306/Task_Tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


app:
  jwt-refresh-secret: 11445bc6636696a201bcaca5e817a577cb4611c1cd5e5404ebe9dd2b575059c1fdb6a73b0a1af7e46c4d24528662067651d4e7ce7f16337033391fcf192aadba
  jwt-access-secret: e9c8eb5128f72241f31a11e73dbcf83ee0c67cfbcacf1141b6a28093d05142e1d9e6d5eaad1db7065da4ab1b5de8a2b962998c86d4b06e6a37f3f765a0626453

  jwt-access-exp: 900000
  jwt-refresh-exp: 604800000
