spring:
  servlet:
    multipart:
      enabled: ${SPRING_SERVLET_MULTIPART_ENABLED:true}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

app:
  jwt-access-secret: ${APP_JWT_ACCESS_SECRET}
  jwt-refresh-secret: ${APP_JWT_REFRESH_SECRET}
  jwt-access-exp: ${APP_JWT_ACCESS_EXP:900000}
  jwt-refresh-exp: ${APP_JWT_REFRESH_EXP:604800000}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}